services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: mi_contrasena
      MYSQL_DATABASE: mi_base
      MYSQL_USER: app_user
      MYSQL_PASSWORD: mi_contrasena
    ports:
      - "3306:3306"
